# Generated by Django 3.2 on 2021-05-10 14:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('council', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activities', models.CharField(blank=True, max_length=500, null=True)),
                ('work_to_be_done', models.CharField(blank=True, max_length=500, null=True)),
                ('week_starting', models.DateField(null=True)),
                ('week_ending', models.DateField(null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='council.employee')),
            ],
            options={
                'ordering': ('created_on',),
            },
        ),
        migrations.CreateModel(
            name='WorkPerformance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('work_done', models.CharField(blank=True, max_length=500, null=True)),
                ('evidence_of_work_done', models.CharField(blank=True, max_length=500, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('supervisor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='superior', to='council.employee')),
                ('work_plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='activities.workplan')),
            ],
            options={
                'ordering': ('created_on',),
            },
        ),
        migrations.CreateModel(
            name='PerfomanceReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment_by_supervisor', models.CharField(blank=True, max_length=100, null=True)),
                ('comment_by_director', models.CharField(blank=True, max_length=100, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('work_performance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='performance', to='activities.workperformance')),
            ],
            options={
                'ordering': ('created_on',),
            },
        ),
    ]
