# Generated by Django 3.2 on 2021-05-13 14:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('council', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyPerfomanceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_starting', models.DateField(null=True)),
                ('week_ending', models.DateField(null=True)),
                ('activity1', models.CharField(blank=True, max_length=500, null=True)),
                ('activity2', models.CharField(blank=True, max_length=500, null=True)),
                ('activity3', models.CharField(blank=True, max_length=500, null=True)),
                ('activity4', models.CharField(blank=True, max_length=500, null=True)),
                ('activity5', models.CharField(blank=True, max_length=500, null=True)),
                ('activity6', models.CharField(blank=True, max_length=500, null=True)),
                ('activity7', models.CharField(blank=True, max_length=500, null=True)),
                ('work_to_be_done1', models.CharField(blank=True, max_length=500, null=True)),
                ('work_to_be_done2', models.CharField(blank=True, max_length=500, null=True)),
                ('work_to_be_done3', models.CharField(blank=True, max_length=500, null=True)),
                ('work_to_be_done4', models.CharField(blank=True, max_length=500, null=True)),
                ('work_to_be_done5', models.CharField(blank=True, max_length=500, null=True)),
                ('work_to_be_done6', models.CharField(blank=True, max_length=500, null=True)),
                ('work_to_be_done7', models.CharField(blank=True, max_length=500, null=True)),
                ('work_done1', models.CharField(blank=True, max_length=500, null=True)),
                ('work_done2', models.CharField(blank=True, max_length=500, null=True)),
                ('work_done3', models.CharField(blank=True, max_length=500, null=True)),
                ('work_done4', models.CharField(blank=True, max_length=500, null=True)),
                ('work_done5', models.CharField(blank=True, max_length=500, null=True)),
                ('evidence_of_work_done1', models.CharField(blank=True, max_length=500, null=True)),
                ('evidence_of_work_done2', models.CharField(blank=True, max_length=500, null=True)),
                ('evidence_of_work_done3', models.CharField(blank=True, max_length=500, null=True)),
                ('evidence_of_work_done4', models.CharField(blank=True, max_length=500, null=True)),
                ('evidence_of_work_done5', models.CharField(blank=True, max_length=500, null=True)),
                ('evaluation', models.CharField(blank=True, max_length=500, null=True)),
                ('innovations', models.CharField(blank=True, max_length=500, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_member', to='council.employee')),
            ],
            options={
                'ordering': ('created_on',),
            },
        ),
        migrations.CreateModel(
            name='PerfomanceReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment_by_supervisor', models.CharField(blank=True, max_length=100, null=True)),
                ('checked_and_approved', models.BooleanField(default=False)),
                ('comment_by_director', models.CharField(blank=True, max_length=100, null=True)),
                ('comment_by_assistant_director', models.CharField(blank=True, max_length=100, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('work_performance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='performance', to='activities.weeklyperfomancereview')),
            ],
            options={
                'ordering': ('created_on',),
            },
        ),
    ]
