# Generated by Django 3.2 on 2021-05-13 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklyperfomancereview',
            name='supervisors',
        ),
    ]
